name: "Alert team about detected PII"

on:
  label:
    types: [created]
    
jobs:
  
  alert-team:
    if: github.event.label.name == 'PII Dectected!!'
    runs-on: ubuntu-latest
    
    steps:
      - name: Alert team about detected PII
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
